config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :subcategories
  resources :categories
  resources :authors
  resources :pictures
  post 'carts/add'
  post 'carts/remove'
  resources :books
  devise_for :users
  
  resources :books do
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :pictures
  has_many :author_books
  has_many :authors, through: :author_books
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :pictures
  accepts_nested_attributes_for :authors
  accepts_nested_attributes_for :comments
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    @comments = Comment.all.joins("join books
      on comments.commentable_id = books.id").where("comments.commentable_id=?", @book.id)
    @new_comment = @book.comments.build
    @authors_members = Author.joins(:books)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save!
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { redirect_to @book, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:book_title, :book_isbn, :book_description, :book_price, :subcategory_id, authors_attributes: [:author_name]) #, authors_attributes: [:author_name])#, pictures_attributes: [:path]
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_add_new_comment.html.erb
<main>
  <article>
    <h2>Kommentar hinzufügen: </h2>
    <%= form_with(model: [@book, @new_comment], local: true ) do |form|%>
      <div class="field">
        <%= form.label :comment_title %>
        <%= form.text_field :comment_title %>
        <br>
        <%= form.label :comment_message %>
        <%= form.text_field :comment_message %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </article>
</main>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <main>
    <article>
      <p>
        <strong>Book's name:</strong>
        <%= book.book_title %>
      </p>
      <p>
        <strong>Authors's name:</strong>
        <%= @authors_members[book.id-1].author_name %>
      </p>
      <p>
        <strong>ISBN:</strong>
        <%= book.book_isbn %>
      </p>
      <p>
        <strong>Book's description:</strong>
        <%= book.book_description %>
      </p>
      <p>
        <strong>Price:</strong>
        <%= book.book_price %>
      </p>
      <%= form_with(url: carts_add_path) do |f| %>
        <%= f.hidden_field :id, value: book.id%>
        <%= f.number_field :quantity, value: 1, min: 1 %>
        <% if user_signed_in? %>
          <%= f.submit "Zum Warenkorb hinzufügen"%>
        <% else %>
          <p> Bitte einloggen um Buch zum Warenkorb hinzuzufügen </p>
        <% end %>
      <% end %>
    </main>
  </article>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_area :isbn %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>
<%= render "form", book: @book %>
<br>
<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Books</h1>
<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>
<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= render "form", book: @book %>
<br>
<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @book %>
<% @comments.each do |comment| %>
  <%= render comment %>
  <p>
    <%= link_to "Show this comment", comment %>
  </p>
<% end %>
<%= render "add_new_comment" %>
<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Zu den Subkategorien", subcategories_path %>
  <%= button_to "Destroy this book", @book, method: :delete %>
</div>