config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :subcategories
  resources :categories
  resources :authors
  resources :pictures
  post 'carts/add'
  post 'carts/remove'
  resources :books
  devise_for :users
  
  resources :books do
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  def add
    @book = Book.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    existing_cart = Cart.find_by(user_id: current_user)

    if existing_cart.blank?
      @cart = Cart.new(user: current_user) #, session_token: request.session_options[:id])
      @item = Item.new(book: @book, cart: @cart, quantity: quantity)
      success = @cart.save && @item.save
    elsif Item.find_by(book_id: params[:id]).blank?
      @cart = existing_cart
      @item = Item.new(book: @book, cart: @cart, quantity: quantity)
      success = @item.save
    else
      @item = Item.find_by(cart_id: existing_cart.id, book_id: @book.id)
      @item.book = @book
      @item.quantity = quantity
      success = @item.update(quantity: quantity)
    end

    respond_to do |format|
      if success
        format.html { redirect_to controller: "books", action: "show", id: params[:id] }
        format.json { render json: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove
    Item.find_by(id: params[:id]).destroy
    existing_cart = Cart.find_by(user_id: current_user)

    if Item.find_by(cart_id: existing_cart).blank?
      respond_to do |format|
        if existing_cart.destroy
          format.html { redirect_to controller: "books", action: "show", id: params[:id] }
          format.json { render json: @item }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<aside>
  <div class=cart>
    <h1>Warenkorb</h1>
    <p style="color: green"><%= notice %></p>
    <% @items.each do |item| %>
      <p>
        <strong>Buchtitel:</strong>
        <%= item.book.book_title %>
      </p>
      <p>
        <strong>Menge:</strong>
        <%= item.quantity %>
      </p>
      <p>
        <strong>Preis:</strong>
        <%= item.book.book_price %>
      </p>
      <%= form_with(url: carts_remove_path) do |f| %>
        <%= f.hidden_field :id, value: item.id%>
        <%= f.submit "Artikel entfernen"%>
      <% end %>
      <strong>Summe gesamt: </strong>
      <%=item.total%>
    <% end %>
  </div>
</aside>

app/views/carts/_form.html.erb
<%= form_with(model: carts) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carts.errors.count, "error") %> prohibited this cart from being saved:</h2>
      <ul>
        <% carts.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>
<%= render "form", cart: @cart %>
<br>
<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Carts</h1>
<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>
<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>
<%= render "form", cart: @cart %>
<br>
<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @cart %>
<div>
  <%= link_to "Edit this cart", edit_cart_path(@cart) %> |
  <%= link_to "Back to carts", carts_path %>
  <%= button_to "Destroy this cart", @cart, method: :delete %>
</div>