config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :subcategories
  resources :categories
  resources :authors
  resources :pictures
  post 'carts/add'
  post 'carts/remove'
  resources :books
  devise_for :users
  
  resources :books do
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#index"
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @book_subcategories = Subcategory.all.joins("join categories
      on subcategories.category_id = categories.id").where("subcategories.category_id=?", @category.id)
    @subcategory = Subcategory.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:category_name, :category_description)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_add_new_subcategory.html.erb
<h2>Buch zum Shop hinzufügen: </h2>
<%= form_with(model: [@subcategory], local: true ) do |form|%>
  <div class="field">
    <%= form.hidden_field :category_id, value: @category.id %>
    <%= form.label :subcategory_topic %>
    <%= form.text_field :subcategory_topic %>
    <br>
    <%= form.label :subcategory_description %>
    <%= form.text_field :subcategory_description %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Sachbuchkategorie:</strong>
    <%= category.category_name %>
  </p>
  <p>
    <strong>Kategoriebeschreibung:</strong>
    <%= category.category_description %>
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :category_name, style: "display: block" %>
  <%= form.text_field :category_name %>
  <%= form.label :category_description, style: "display: block" %>
  <%= form.text_field :category_description %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>
<%= render "form", category: @category %>
<br>
<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Hauptkategorien</h1>
<div class="navbar_items">
  <% @categories.each do |category| %>
    <%= link_to category.category_name, category %>
  <% end %>
</div>
<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render "form", category: @category %>
<br>
<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="navbar_items">
  <% @book_subcategories.each do |subcategory| %>
    <%= link_to subcategory.subcategory_topic, subcategory %>
  <% end %>
  <%= link_to "Zur Hauptkategorie", categories_path %>
</div>
<%= render "add_new_subcategory" %>
<%= link_to "Edit this subcategory", edit_subcategory_path(@category) %>
<%= link_to "Back to categories", categories_path %>
<%= button_to "Destroy this subcategory", @subcategory, method: :delete %>